### ISSUE TITLE
500 thrown for invalid jwt signiture

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acrontum/generate-it-typescript-server#52]
https://github.com/acrontum/generate-it-typescript-server/blob/master/src/services/AccessTokenService.ts#L138

As the title says - it should not throw a 500 as this indicate an error in the server code.. but it is actually invalid content from the client so should be a 401 maybe?

@p-mcgowan   @acrontum-sanchez    what's your opinion?

I hit this error when working locally then pointing my local frontend code to the stage env which used a different jwt secret:

```
0|ms-authentication  | [ms-authentication] 2020-10-01T13:23:37.536Z error: JsonWebTokenError: invalid signature
0|ms-authentication  |     at /var/www/node/ms-authentication/node_modules/jsonwebtoken/verify.js:133:19
0|ms-authentication  |     at getSecret (/var/www/node/ms-authentication/node_modules/jsonwebtoken/verify.js:90:14)
0|ms-authentication  |     at Object.module.exports [as verify] (/var/www/node/ms-authentication/node_modules/jsonwebtoken/verify.js:94:10)
0|ms-authentication  |     at /var/www/node/ms-authentication/src/services/AccessTokenService.ts:116:11
0|ms-authentication  |     at new Promise (<anonymous>)
0|ms-authentication  |     at AccessTokenService.verifyJWT (/var/www/node/ms-authentication/src/services/AccessTokenService.ts:115:12)
0|ms-authentication  |     at TokenDomain.tokenRenewAccessPost (/var/www/node/ms-authentication/src/domains/TokenDomain.ts:10:51)
0|ms-authentication  |     at /var/www/node/ms-authentication/src/http/nodegen/routes/tokenRoutes.ts:33:31
0|ms-authentication  |     at handleReturn (/var/www/node/ms-authentication/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
0|ms-authentication  |     at /var/www/node/ms-authentication/node_modules/express-promise-router/lib/express-promise-router.js:56:9
0|ms-authentication  |     at handleReturn (/var/www/node/ms-authentication/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
0|ms-authentication  |     at /var/www/node/ms-authentication/node_modules/express-promise-router/lib/express-promise-router.js:56:9
0|ms-authentication  |     at Layer.handle [as handle_request] (/var/www/node/ms-authentication/node_modules/express/lib/router/layer.js:95:5)
0|ms-authentication  |     at next (/var/www/node/ms-authentication/node_modules/express/lib/router/route.js:137:13)
0|ms-authentication  |     at runMicrotasks (<anonymous>)
0|ms-authentication  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) 
0|ms-authentication  | [ms-authentication] ::1 [01/Oct/2020:13:23:37 +0000] "POST /token/renew/access HTTP/1.1" 500 31

```

**Comment by acrontum-sanchez** [comment]
Definitively, an invalid signature should return a 401.

**Comment by p-mcgowan** [comment]
Yup - 401 for missing / un-parsable token / auth, 403 if you are authenticated but not allowed to access something

**Comment by Acrontum-Carmichael** [comment]
agreed - will create a PR
